"""create_financial_tables

Revision ID: 9d37f737e7ed
Revises: 
Create Date: 2026-08-23 22:52:50.577421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d37f737e7ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=256), nullable=False),
    sa.Column('publisher', sa.String(length=160), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_sources_name'), 'financial_sources', ['name'], unique=True)
    op.create_table('financial_import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('fiscal_year', sa.String(length=16), nullable=False),
    sa.Column('records_parsed', sa.Integer(), nullable=False),
    sa.Column('records_approved', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['financial_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_import_runs_fiscal_year'), 'financial_import_runs', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_import_runs_source_id'), 'financial_import_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_financial_import_runs_status'), 'financial_import_runs', ['status'], unique=False)
    op.create_table('financial_raw_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['financial_import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_raw_snapshots_checksum_sha256'), 'financial_raw_snapshots', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_financial_raw_snapshots_import_run_id'), 'financial_raw_snapshots', ['import_run_id'], unique=False)
    op.create_table('financial_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(length=8), nullable=True),
    sa.Column('district_code', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('scheme_code', sa.String(length=64), nullable=True),
    sa.Column('scheme_name', sa.String(length=256), nullable=False),
    sa.Column('financial_stage', sa.String(length=16), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fiscal_year', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('coverage', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['financial_import_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['financial_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fin_lookup', 'financial_records', ['fiscal_year', 'state_code', 'district_code', 'category', 'financial_stage'], unique=False)
    op.create_index('ix_fin_status', 'financial_records', ['verification_status', 'financial_stage'], unique=False)
    op.create_index(op.f('ix_financial_records_category'), 'financial_records', ['category'], unique=False)
    op.create_index(op.f('ix_financial_records_district_code'), 'financial_records', ['district_code'], unique=False)
    op.create_index(op.f('ix_financial_records_financial_stage'), 'financial_records', ['financial_stage'], unique=False)
    op.create_index(op.f('ix_financial_records_fiscal_year'), 'financial_records', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_records_import_run_id'), 'financial_records', ['import_run_id'], unique=False)
    op.create_index(op.f('ix_financial_records_scheme_code'), 'financial_records', ['scheme_code'], unique=False)
    op.create_index(op.f('ix_financial_records_source_id'), 'financial_records', ['source_id'], unique=False)
    op.create_index(op.f('ix_financial_records_state_code'), 'financial_records', ['state_code'], unique=False)
    op.create_index(op.f('ix_financial_records_verification_status'), 'financial_records', ['verification_status'], unique=False)
    op.create_table('financial_record_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_role', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['financial_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_record_reviews_record_id'), 'financial_record_reviews', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_record_reviews_record_id'), table_name='financial_record_reviews')
    op.drop_table('financial_record_reviews')
    op.drop_index(op.f('ix_financial_records_verification_status'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_state_code'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_source_id'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_scheme_code'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_import_run_id'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_fiscal_year'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_financial_stage'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_district_code'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_category'), table_name='financial_records')
    op.drop_index('ix_fin_status', table_name='financial_records')
    op.drop_index('ix_fin_lookup', table_name='financial_records')
    op.drop_table('financial_records')
    op.drop_index(op.f('ix_financial_raw_snapshots_import_run_id'), table_name='financial_raw_snapshots')
    op.drop_index(op.f('ix_financial_raw_snapshots_checksum_sha256'), table_name='financial_raw_snapshots')
    op.drop_table('financial_raw_snapshots')
    op.drop_index(op.f('ix_financial_import_runs_status'), table_name='financial_import_runs')
    op.drop_index(op.f('ix_financial_import_runs_source_id'), table_name='financial_import_runs')
    op.drop_index(op.f('ix_financial_import_runs_fiscal_year'), table_name='financial_import_runs')
    op.drop_table('financial_import_runs')
    op.drop_index(op.f('ix_financial_sources_name'), table_name='financial_sources')
    op.drop_table('financial_sources')
    # ### end Alembic commands ###
